# Naive Bayes

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np

In [5]:
import os
path=r'C:\Users\ANIL\Desktop\python\DATASETS\New folder\beginner_datasets'
os.chdir(path)

In [12]:
df = pd.read_csv('automobile.csv')
df

symboling  normalized-losses         make fuel-type aspiration  \
0            3                NaN  alfa-romero       gas        std   
1            3                NaN  alfa-romero       gas        std   
2            1                NaN  alfa-romero       gas        std   
3            2              164.0         audi       gas        std   
4            2              164.0         audi       gas        std   
..         ...                ...          ...       ...        ...   
197         -1               95.0        volvo       gas      turbo   
198         -1               95.0        volvo       gas        std   
199         -1               95.0        volvo    diesel      turbo   
200         -1               95.0        volvo       gas      turbo   
201         -1               95.0        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...   
1            two  convertible          rwd           front        88.6  ...   
2            two    hatchback          rwd           front        94.5  ...   
3           four        sedan          fwd           front        99.8  ...   
4           four        sedan          4wd           front        99.4  ...   
..           ...          ...          ...             ...         ...  ...   
197         four        sedan          rwd           front       109.1  ...   
198         four        sedan          rwd           front       109.1  ...   
199         four        sedan          rwd           front       109.1  ...   
200         four        sedan          rwd           front       109.1  ...   
201         four        sedan          rwd           front       109.1  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111   
1            130         mpfi  3.47    2.68               9.0        111   
2            152         mpfi  2.68    3.47               9.0        154   
3            109         mpfi  3.19     3.4              10.0        102   
4            136         mpfi  3.19     3.4               8.0        115   
..           ...          ...   ...     ...               ...        ...   
197          141         mpfi  3.78    3.15               8.7        160   
198          173         mpfi  3.58    2.87               8.8        134   
199          145          idi  3.01     3.4              23.0        106   
200          141         mpfi  3.78    3.15               9.5        114   
201          141         mpfi  3.78    3.15               9.5        114   

     peak-rpm city-mpg highway-mpg  price  
0        5000       21          27  13495  
1        5000       21          27  16500  
2        5000       19          26  16500  
3        5500       24          30  13950  
4        5500       18          22  17450  
..        ...      ...         ...    ...  
197      5300       19          25  19045  
198      5500       18          23  21485  
199      4800       26          27  22470  
200      5400       19          25  22625  
201      5400       19          25  22625  

[202 rows x 26 columns]

In [13]:
df.shape

(202, 26)

In [14]:
df.isnull().sum()

symboling             0
normalized-losses    37
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  0
stroke                0
compression-ratio     0
horsepower            0
peak-rpm              0
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [15]:
df.describe()

symboling  normalized-losses  wheel-base      length       width  \
count  202.000000         165.000000  202.000000  202.000000  202.000000   
mean     0.831683         121.836364   98.848020  174.273267   65.903960   
std      1.258360          35.396412    6.094523   12.334330    2.106915   
min     -2.000000          65.000000   86.600000  141.100000   60.300000   
25%      0.000000          94.000000   94.500000  166.800000   64.125000   
50%      1.000000         115.000000   97.000000  173.200000   65.500000   
75%      2.000000         150.000000  102.400000  183.500000   66.825000   
max      3.000000         256.000000  120.900000  208.100000   72.000000   

           height  curb-weight  engine-size  compression-ratio    city-mpg  \
count  202.000000   202.000000   202.000000         202.000000  202.000000   
mean    53.775248  2558.173267   126.945545          10.160990   25.148515   
std      2.444769   517.236654    41.455269           3.995264    6.421956   
min     47.800000  1488.000000    61.000000           7.000000   13.000000   
25%     52.000000  2174.250000    98.000000           8.600000   19.000000   
50%     54.100000  2417.000000   120.000000           9.000000   24.000000   
75%     55.500000  2932.750000   141.000000           9.400000   30.000000   
max     59.800000  4066.000000   326.000000          23.000000   49.000000   

       highway-mpg         price  
count   202.000000    202.000000  
mean     30.658416  13253.752475  
std       6.809940   7954.919591  
min      16.000000   5118.000000  
25%      25.000000   7778.250000  
50%      30.000000  10320.000000  
75%      34.000000  16502.250000  
max      54.000000  45400.000000

In [16]:
df['normalized-losses'].fillna(df['normalized-losses'].mean())

0      121.836364
1      121.836364
2      121.836364
3      164.000000
4      164.000000
          ...    
197     95.000000
198     95.000000
199     95.000000
200     95.000000
201     95.000000
Name: normalized-losses, Length: 202, dtype: float64

In [17]:
df.isnull().sum()

symboling             0
normalized-losses    37
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  0
stroke                0
compression-ratio     0
horsepower            0
peak-rpm              0
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          202 non-null    int64  
 1   normalized-losses  165 non-null    float64
 2   make               202 non-null    object 
 3   fuel-type          202 non-null    object 
 4   aspiration         202 non-null    object 
 5   num-of-doors       200 non-null    object 
 6   body-style         202 non-null    object 
 7   drive-wheels       202 non-null    object 
 8   engine-location    202 non-null    object 
 9   wheel-base         202 non-null    float64
 10  length             202 non-null    float64
 11  width              202 non-null    float64
 12  height             202 non-null    float64
 13  curb-weight        202 non-null    int64  
 14  engine-type        202 non-null    object 
 15  num-of-cylinders   202 non-null    object 
 16  engine-size        202 non

In [19]:
from sklearn import preprocessing
  
label_encoder = preprocessing.LabelEncoder()
def StrToFloat(x):
    df[x]= label_encoder.fit_transform(df[x])
    df[x].unique()
for i in df.columns:
    StrToFloat(i)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          202 non-null    int64
 1   normalized-losses  202 non-null    int64
 2   make               202 non-null    int32
 3   fuel-type          202 non-null    int32
 4   aspiration         202 non-null    int32
 5   num-of-doors       202 non-null    int32
 6   body-style         202 non-null    int32
 7   drive-wheels       202 non-null    int32
 8   engine-location    202 non-null    int32
 9   wheel-base         202 non-null    int64
 10  length             202 non-null    int64
 11  width              202 non-null    int64
 12  height             202 non-null    int64
 13  curb-weight        202 non-null    int64
 14  engine-type        202 non-null    int32
 15  num-of-cylinders   202 non-null    int32
 16  engine-size        202 non-null    int64
 17  fuel-system     

In [21]:
df

symboling  normalized-losses  make  fuel-type  aspiration  num-of-doors  \
0            5                 51     0          1           0             1   
1            5                 51     0          1           0             1   
2            3                 51     0          1           0             1   
3            4                 42     1          1           0             0   
4            4                 42     1          1           0             0   
..         ...                ...   ...        ...         ...           ...   
197          1                 13    21          1           1             0   
198          1                 13    21          1           0             0   
199          1                 13    21          0           1             0   
200          1                 13    21          1           1             0   
201          1                 13    21          1           1             0   

     body-style  drive-wheels  engine-location  wheel-base  ...  engine-size  \
0             0             2                0           2  ...           18   
1             0             2                0           2  ...           18   
2             2             2                0          10  ...           28   
3             3             1                0          29  ...           11   
4             3             0                0          28  ...           22   
..          ...           ...              ...         ...  ...          ...   
197           3             2                0          45  ...           24   
198           3             2                0          45  ...           33   
199           3             2                0          45  ...           25   
200           3             2                0          45  ...           24   
201           3             2                0          45  ...           24   

     fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  \
0              5    23       4                 13           5        10   
1              5    23       4                 13           5        10   
2              5     1      27                 13          20        10   
3              5    13      24                 22           2        16   
4              5    13      24                  5           8        16   
..           ...   ...     ...                ...         ...       ...   
197            5    35      15                 11          23        14   
198            5    26       7                 12          13        16   
199            3     6      24                 31           3         8   
200            5    35      15                 20           7        15   
201            5    35      15                 20           7        15   

     city-mpg  highway-mpg  price  
0           8           10    117  
1           8           10    136  
2           6            9    136  
3          11           13    122  
4           5            5    147  
..        ...          ...    ...  
197         6            8    159  
198         5            6    163  
199        13           10    165  
200         6            8    166  
201         6            8    166  

[202 rows x 26 columns]

In [22]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [23]:
df['length']

0      22
1      22
2      29
3      44
4      44
       ..
197    61
198    61
199    61
200    61
201    61
Name: length, Length: 202, dtype: int64

In [24]:
df['width']

0       8
1       8
2      16
3      21
4      23
       ..
197    33
198    34
199    34
200    34
201    34
Name: width, Length: 202, dtype: int64

In [25]:
df['height']

0       1
1       1
2      13
3      25
4      25
       ..
197    34
198    34
199    34
200    34
201    34
Name: height, Length: 202, dtype: int64

In [26]:
df['curb-weight']

0       92
1       92
2      115
3       66
4      116
      ... 
197    135
198    129
199    150
200    138
201    138
Name: curb-weight, Length: 202, dtype: int64

In [27]:
df['engine-type']

0      0
1      0
2      4
3      2
4      2
      ..
197    2
198    4
199    2
200    2
201    2
Name: engine-type, Length: 202, dtype: int32

In [28]:
df['num-of-cylinders']

0      2
1      2
2      3
3      2
4      1
      ..
197    2
198    3
199    3
200    2
201    2
Name: num-of-cylinders, Length: 202, dtype: int32

## Splitting the dataset into the Training set and Test set

In [29]:
X=df[['normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price']]
y=df['symboling']

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [31]:
print(X_train)

     normalized-losses  make  fuel-type  aspiration  num-of-doors  body-style  \
96                  19    12          1           0             0           2   
182                 12    20          1           0             0           3   
19                   4     3          1           0             0           3   
153                 10    19          1           0             0           2   
92                  30    12          1           0             1           2   
..                 ...   ...        ...         ...           ...         ...   
67                  11     9          0           1             0           3   
192                 17    21          1           0             0           3   
117                 39    14          1           0             0           2   
47                  18     8          1           0             1           2   
172                  0    19          1           0             0           3   

     drive-wheels  engine-l

In [32]:
print(y_train)

96     2
182    4
19     2
153    2
92     3
      ..
67     1
192    0
117    3
47     3
172    1
Name: symboling, Length: 141, dtype: int64


In [33]:
print(X_test)

     normalized-losses  make  fuel-type  aspiration  num-of-doors  body-style  \
18                  14     3          1           0             1           2   
171                  0    19          1           0             0           2   
107                 51    13          0           1             0           4   
98                  30    12          1           0             0           3   
178                 28    20          0           0             1           3   
..                 ...   ...        ...         ...           ...         ...   
30                  33     5          1           0             1           2   
160                 43    19          1           0             1           2   
40                   6     5          1           0             0           3   
56                  31     8          1           0             1           2   
131                 18    17          1           0             0           3   

     drive-wheels  engine-l

In [34]:
print(y_test)

18     3
171    1
107    2
98     2
178    4
      ..
30     4
160    3
40     2
56     3
131    4
Name: symboling, Length: 61, dtype: int64


## Feature Scaling

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [36]:
print(X_train)

[[-0.56630671 -0.06411941  0.27628948 ...  0.32812948  0.64020683
  -0.38502942]
 [-1.00572866  1.2274287   0.27628948 ...  0.32812948  0.64020683
  -0.51702804]
 [-1.50792517 -1.51711104  0.27628948 ...  2.17207447  1.8483983
  -1.34673367]
 ...
 [ 0.68918458  0.25876762  0.27628948 ...  0.99865493  1.15800317
  -1.47873229]
 [-0.62908127 -0.70989347  0.27628948 ...  0.83102357  0.12241048
  -1.62958786]
 [-1.75902343  1.06598519  0.27628948 ...  0.32812948  0.29500926
   0.08639424]]


In [37]:
print(X_test)

[[-0.88017953 -1.51711104  0.27628948 ...  2.17207447  1.8483983
  -1.45987535]
 [-1.75902343  1.06598519  0.27628948 ...  0.32812948  0.29500926
  -0.10217523]
 [ 1.44247935  0.0973241  -3.61939221 ... -0.00713325 -0.9131822
   0.61438873]
 ...
 [-1.38237604 -1.19422401  0.27628948 ... -0.17476461 -0.39538586
   0.44467621]
 [ 0.18698806 -0.70989347  0.27628948 ...  0.16049811  0.29500926
  -0.44160026]
 [-0.62908127  0.74309816  0.27628948 ... -0.6776587  -0.39538586
   0.74638735]]


## Training the Naive Bayes model on the Training set

In [38]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [39]:
df

symboling  normalized-losses  make  fuel-type  aspiration  num-of-doors  \
0            5                 51     0          1           0             1   
1            5                 51     0          1           0             1   
2            3                 51     0          1           0             1   
3            4                 42     1          1           0             0   
4            4                 42     1          1           0             0   
..         ...                ...   ...        ...         ...           ...   
197          1                 13    21          1           1             0   
198          1                 13    21          1           0             0   
199          1                 13    21          0           1             0   
200          1                 13    21          1           1             0   
201          1                 13    21          1           1             0   

     body-style  drive-wheels  engine-location  wheel-base  ...  engine-size  \
0             0             2                0           2  ...           18   
1             0             2                0           2  ...           18   
2             2             2                0          10  ...           28   
3             3             1                0          29  ...           11   
4             3             0                0          28  ...           22   
..          ...           ...              ...         ...  ...          ...   
197           3             2                0          45  ...           24   
198           3             2                0          45  ...           33   
199           3             2                0          45  ...           25   
200           3             2                0          45  ...           24   
201           3             2                0          45  ...           24   

     fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  \
0              5    23       4                 13           5        10   
1              5    23       4                 13           5        10   
2              5     1      27                 13          20        10   
3              5    13      24                 22           2        16   
4              5    13      24                  5           8        16   
..           ...   ...     ...                ...         ...       ...   
197            5    35      15                 11          23        14   
198            5    26       7                 12          13        16   
199            3     6      24                 31           3         8   
200            5    35      15                 20           7        15   
201            5    35      15                 20           7        15   

     city-mpg  highway-mpg  price  
0           8           10    117  
1           8           10    136  
2           6            9    136  
3          11           13    122  
4           5            5    147  
..        ...          ...    ...  
197         6            8    159  
198         5            6    163  
199        13           10    165  
200         6            8    166  
201         6            8    166  

[202 rows x 26 columns]

## Predicting a new result

In [40]:
print(classifier.predict(sc.transform([[51,0,1,0,1,0,2,0,2,22,8,1,92,0,2,18,5,23,4,13,5,10,8,10,117]])))

[5]


## Predicting the Test set results

In [41]:
y_pred = classifier.predict(X_test)
print(np.concatenate((np.array(y_pred).reshape(len(y_pred),1), np.array(y_test).reshape(len(y_test),1)),1))

[[4 3]
 [4 1]
 [1 2]
 [1 2]
 [2 4]
 [2 4]
 [5 4]
 [4 3]
 [1 2]
 [4 2]
 [4 2]
 [5 5]
 [4 4]
 [2 2]
 [5 5]
 [1 3]
 [4 3]
 [5 5]
 [4 2]
 [4 4]
 [5 5]
 [1 2]
 [1 2]
 [4 3]
 [2 2]
 [5 5]
 [2 4]
 [4 5]
 [5 5]
 [1 2]
 [1 2]
 [5 5]
 [4 2]
 [1 2]
 [5 3]
 [0 0]
 [1 4]
 [1 4]
 [4 3]
 [1 2]
 [4 4]
 [2 2]
 [3 3]
 [1 2]
 [4 1]
 [1 2]
 [1 3]
 [4 4]
 [4 3]
 [4 2]
 [5 3]
 [5 5]
 [4 5]
 [4 2]
 [4 2]
 [3 3]
 [4 4]
 [4 3]
 [4 2]
 [4 3]
 [1 4]]


## Making the Confusion Matrix

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 1  0  0  0  0  0]
 [ 0  0  0  0  2  0]
 [ 0 11  3  0  8  0]
 [ 0  2  0  2  8  2]
 [ 0  3  3  0  5  1]
 [ 0  0  0  0  2  8]]


0.3114754098360656

## Visualising the Training set results

In [43]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Naive Bayes (Training set)')
plt.xlabel('Recency', 'Frequency', 'Monetary', 'Time')
plt.ylabel('Class')
plt.legend()
plt.show()

ValueError: X has 2 features, but StandardScaler is expecting 25 features as input.

## Visualising the Test set results

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_test), y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Naive Bayes (Test set)')
plt.xlabel('Recency')
plt.ylabel('Class')
plt.legend()
plt.show()