# Naive Bayes

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np

In [2]:
import os
path=r'C:\Users\ANIL\Desktop\python\DATASETS\New folder\archive (5)\beginner_datasets'
os.chdir(path)

In [3]:
df = pd.read_csv('blood.csv')
df


Recency  Frequency  Monetary  Time  Class
0          2         50     12500    98      1
1          0         13      3250    28      1
2          1         16      4000    35      1
3          2         20      5000    45      1
4          1         24      6000    77      0
..       ...        ...       ...   ...    ...
743       23          2       500    38      0
744       21          2       500    52      0
745       23          3       750    62      0
746       39          1       250    39      0
747       72          1       250    72      0

[748 rows x 5 columns]

In [4]:
df['Recency'].unique()

array([ 2,  0,  1,  4,  5,  9,  3, 12,  6, 11, 10, 13,  8, 14,  7, 16, 15,
       23, 21, 18, 22, 26, 35, 38, 40, 74, 20, 17, 25, 39, 72],
      dtype=int64)

In [5]:
df['Frequency'].unique()

array([50, 13, 16, 20, 24,  4,  7, 12,  9, 46, 23,  3, 10,  6,  5, 14, 15,
       11,  8,  2, 19, 17,  1, 22, 18, 38, 43, 34, 44, 26, 41, 21, 33],
      dtype=int64)

In [6]:
df.isnull().sum()

Recency      0
Frequency    0
Monetary     0
Time         0
Class        0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Recency    748 non-null    int64
 1   Frequency  748 non-null    int64
 2   Monetary   748 non-null    int64
 3   Time       748 non-null    int64
 4   Class      748 non-null    int64
dtypes: int64(5)
memory usage: 29.3 KB


In [8]:
df.columns

Index(['Recency', 'Frequency', 'Monetary', 'Time', 'Class'], dtype='object')

## Splitting the dataset into the Training set and Test set

In [9]:
X=df[['Recency', 'Frequency', 'Monetary', 'Time']]
y=df['Class']

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [11]:
print(X_train)

     Recency  Frequency  Monetary  Time
449       16          3       750    50
235        8         10      2500    63
325       14          2       500    16
77         2          2       500     4
363       21         13      3250    57
..       ...        ...       ...   ...
707       11          4      1000    74
192        2          4      1000    35
629        7         11      2750    89
559        3          8      2000    50
684       16          4      1000    33

[561 rows x 4 columns]


In [12]:
print(y_train)

449    0
235    0
325    0
77     0
363    0
      ..
707    0
192    0
629    0
559    0
684    0
Name: Class, Length: 561, dtype: int64


In [13]:
print(X_test)

     Recency  Frequency  Monetary  Time
258        4          3       750    28
521        2         11      2750    41
14         2          6      1500    15
31         4         10      2500    28
505        2         41     10250    98
..       ...        ...       ...   ...
255        2          3       750    35
21         4         11      2750    28
593        9         11      2750    49
386       14          1       250    14
35         2          8      2000    28

[187 rows x 4 columns]


In [14]:
print(y_test)

258    0
521    1
14     1
31     1
505    1
      ..
255    0
21     0
593    1
386    0
35     1
Name: Class, Length: 187, dtype: int64


## Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
print(X_train)

[[ 0.83389889 -0.41908973 -0.41908973  0.63647224]
 [-0.19314233  0.81554296  0.81554296  1.16665979]
 [ 0.57713859 -0.59546583 -0.59546583 -0.75017213]
 ...
 [-0.32152249  0.99191906  0.99191906  2.22703489]
 [-0.8350431   0.46279076  0.46279076  0.63647224]
 [ 0.83389889 -0.24271363 -0.24271363 -0.05684995]]


In [17]:
print(X_test)

[[-0.70666295 -0.41908973 -0.41908973 -0.26076824]
 [-0.96342325  0.99191906  0.99191906  0.26941932]
 [-0.96342325  0.11003856  0.11003856 -0.79095579]
 [-0.70666295  0.81554296  0.81554296 -0.26076824]
 [-0.96342325  6.28320204  6.28320204  2.59408782]
 [-0.96342325 -0.59546583 -0.59546583 -1.23957603]
 [ 0.57713859 -0.77184193 -0.77184193 -0.83173945]
 [-0.96342325 -0.59546583 -0.59546583 -1.23957603]
 [ 1.73255997 -0.41908973 -0.41908973  0.22863566]
 [-0.70666295  1.16829516  1.16829516 -0.01606629]
 [ 0.19199813  0.11003856  0.11003856  0.26941932]
 [ 0.57713859 -0.24271363 -0.24271363  0.14706834]
 [-0.96342325 -0.77184193 -0.77184193 -1.32114334]
 [-0.70666295  1.34467126  1.34467126  0.187852  ]
 [-0.96342325  1.34467126  1.34467126  0.75882321]
 [ 1.73255997  0.46279076  0.46279076  1.41136174]
 [-0.19314233 -0.59546583 -0.59546583 -0.75017213]
 [ 1.47579966 -0.77184193 -0.77184193 -0.54625384]
 [ 0.57713859  0.28641466  0.28641466  1.53371271]
 [-0.70666295  0.46279076  0.46

## Training the Naive Bayes model on the Training set

In [18]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

## Predicting a new result

In [19]:
print(classifier.predict(sc.transform([[-0.96342325, 0.99191906,  0.99191906,  0.22863566]])))

[0]


## Predicting the Test set results

In [20]:
y_pred = classifier.predict(X_test)
print(np.concatenate((np.array(y_pred).reshape(len(y_pred),1),np.array(y_test).reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]

## Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[124   8]
 [ 42  13]]


0.732620320855615

## Visualising the Training set results

In [22]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Naive Bayes (Training set)')
plt.xlabel('Recency', 'Frequency', 'Monetary', 'Time')
plt.ylabel('Class')
plt.legend()
plt.show()

ValueError: X has 2 features, but StandardScaler is expecting 4 features as input.

## Visualising the Test set results

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_test), y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Naive Bayes (Test set)')
plt.xlabel('Recency')
plt.ylabel('Class')
plt.legend()
plt.show()